package mirrorsync

import (
	"context"
	"testing"

	"mirror-server/internal/config"
	mastercontrol "mirror-server/internal/master/control"
)

func TestSyncProjectConfigNotifiesRuntimeWhenDeleteTasksGenerated(t *testing.T) {
	db, store := seedProjectConfigTask(t)
	defer db.Close()
	mustExecRetry(t, db, `INSERT INTO node_inventory
		(node_id, asset_id, local_digest_sha256, size_bytes, verified_at, state)
		VALUES ('node-1', 'p1:1:1',
		'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
		10, 'now', 'verified')`)
	runtime := mastercontrol.NewRuntimeStore()
	runtime.StartSession(mastercontrol.Session{ID: "sess-1", NodeID: "node-1"})
	store.Runtime = runtime
	disabled := config.Projects{Projects: []config.Project{testProject("p1", "owner/repo", false)}}

	if err := store.SyncProjectConfig(context.Background(), disabled); err != nil {
		t.Fatal(err)
	}
	assertWhereCount(t, db, "node_tasks", "task_type = 'asset_delete' AND state = 'pending'", 1)
	if !runtime.ConsumeSyncTaskWake("node-1") {
		t.Fatal("delete task generated by config change should notify active node")
	}
}
